sudo: required
language: java

services:
  - docker

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_script:
- echo "$CONFIG" | base64 --decode > gcloud-config.json
- chmod +x gradlew
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud auth activate-service-account --key-file gcloud-config.json
- gcloud -q components update
- gcloud -q auth configure-docker
- gcloud -q version
- gcloud -q components install kubectl
- gcloud container clusters get-credentials jasoet-research --zone asia-southeast1-a --project jasoet-research
- gcloud config set compute/zone asia-southeast1-a
- gcloud config set project jasoet-research

script:
- "./gradlew check build dockerPush -Ptag=${TRAVIS_COMMIT"}"

after_success:
- bash <(curl -s https://codecov.io/bash) -t 5ad8bf57-2558-4973-a1dc-762de9a531d6
- "kubectl set image deployment/wof-scheduler wof=gcr.io/jasoet-research/wof-scheduler:${TRAVIS_COMMIT}"
