# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/engineers/populate
Accepts: application/json

###

GET http://localhost:8080/engineers
Accepts: application/json

###

DELETE http://localhost:8080/engineers/1

###

POST http://localhost:8080/engineers
Content-Type: application/json

{
 "id": 1,
 "name": "New Engineer On the Block"
}
###
